name: Deploy to VDS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: '22'
          script: |
            cd /${{ secrets.VDS_USER }}/remyzonk

            echo "APP_NAME=Laravel" > .env
            echo "APP_ENV=prod" >> .env
            echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            echo "APP_URL=${{ secrets.APP_URL }}" >> .env
            echo "APP_LOCALE=ru" >> .env
            echo "APP_FALLBACK_LOCALE=ru" >> .env
            echo "APP_TIMEZONE=Europe/Moscow" >> .env
            echo "LOG_CHANNEL=stack" >> .env
            echo "LOG_LEVEL=debug" >> .env
            echo "DB_CONNECTION=pgsql" >> .env
            echo "DB_HOST=db" >> .env
            echo "DB_PORT=5432" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "SESSION_DRIVER=database" >> .env
            echo "SESSION_LIFETIME=120" >> .env
            echo "REDIS_CLIENT=phpredis" >> .env
            echo "REDIS_HOST=redis" >> .env
            echo "REDIS_PORT=6379" >> .env
            echo "QUEUE_CONNECTION=database" >> .env
            echo "CACHE_STORE=database" >> .env
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            
            ./deploy.sh
